### ISSUE TITLE
Logo For Nurse Rostering

### ISSUE THREAD

**Issue by zularizal** [JonathanHolland/NurseRostering#2]
Hi @JonathanHolland ,I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by JonathanHolland** [comment]
Hey Zularizal - you're more than welcome to design a logo for this application if you're looking at improving your skills and getting your brand out there. Please be aware though I intend to release this application on the app store for free when I finally complete it!

**Comment by CaptainAchilles** [comment]
I would hope so, since you are licensing it under the openGPLv3

**Comment by MrCeleryman** [comment]
I hope you are also including a link to the source code of the app on your app that is easily accessible.

**Comment by zularizal** [comment]
Hi, I've made some logos for you, what do you think?
Which one do you like? If there is something you want to change please let me know

This logo can work under the GPL v3 license.
I will send the source file, after you select the logo that you like.

![logo](https://user-images.githubusercontent.com/38547278/42482925-baa19400-8414-11e8-87e9-98c06c293d41.png)

**Comment by JonathanHolland** [comment]
Hey Zularizal - sorry for the delay, I really like the first one! I think the third could be misconstrued for an alarm or an emergency timer and the plus button in the second could be mistaken for addition (like adding new items) but the theme is quite crisp and clear in the first design

**Comment by zularizal** [comment]
Hi @JonathanHolland , I've uploaded the logo to drive
https://drive.google.com/open?id=1vbYPE5U3Kbx99SivjCBnxi7t0Oy4FJQf

And also I have sent a pull request for you #3
